image: Visual Studio 2019

environment:
  matrix:
  - solution_path: MyLazy\MyLazy.sln
  - solution_path: MyThreadPool\MyThreadPool.sln
  - solution_path: SimpleFTP\SimpleFTP.sln
	solution_path: Tests\Chat\Chat.sln	solution_path: MyNUnit\MyNUnit.sln
before_build:
  - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%